version: '3.8'
services:
  customer-management-db:
    image: postgres:15
    container_name: customer-management-db
    environment:
      POSTGRES_DB: customer_management_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - customer-management-data:/var/lib/postgresql/data
    networks:
      - supermarket-network
  customer-management-service:
    build: .
    container_name: customer-management-service
    ports:
      - "8082:8082"
    environment:
      DB_HOST: customer-management-db
      DB_PORT: 5432
      DB_NAME: customer_management_db
      DB_USER: postgres
      DB_PASSWORD: postgres
      JASYPT_PASSWORD: secret
    depends_on:
      - customer-management-db
    networks:
      - supermarket-network
volumes:
  customer-management-data:
networks:
  supermarket-network:
    driver: bridge