version: '3.8'
services:
  product-management-db:
    image: postgres:15
    container_name: product-management-db
    environment:
      POSTGRES_DB: product_management_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - product-management-data:/var/lib/postgresql/data
    networks:
      - supermarket-network

  product-management-service:
    build: .
    container_name: product-management-service
    ports:
      - "8083:8083"
    environment:
      DB_HOST: product-management-db
      DB_PORT: 5432
      DB_NAME: product_management_db
      DB_USER: postgres
      DB_PASSWORD: postgres
    depends_on:
      - product-management-db
    networks:
      - supermarket-network

volumes:
  product-management-data:

networks:
  supermarket-network:
    driver: bridge