version: '3.8'
services:
  price-list-management-db:
    image: postgres:15
    container_name: price-list-management-db
    environment:
      POSTGRES_DB: price_list_management_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5435:5432"
    volumes:
      - price-list-management-data:/var/lib/postgresql/data
    networks:
      - supermarket-network
  price-list-management-service:
    build: .
    container_name: price-list-management-service
    ports:
      - "8084:8084"
    environment:
      DB_HOST: price-list-management-db
      DB_PORT: 5432
      DB_NAME: price_list_management_db
      DB_USER: postgres
      DB_PASSWORD: postgres
    depends_on:
      - price-list-management-db
    networks:
      - supermarket-network
volumes:
  price-list-management-data:
networks:
  supermarket-network:
    driver: bridge