server:
  port: 8084
  servlet:
    context-path: /price-list-management
spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:price_list_management_db}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
#    username: ${DB_USER:postgres}
#    password: ${DB_PASSWORD:12345678}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/user-management
application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      expiration: ${JWT_EXPIRATION}
  product-management:
     base-url: ${PRODUCT_MANAGEMENT_URL:http://product-management-service:8083/product-management}
#    base-url: http://localhost:8083/product-management
logging:
  level:
    org.springframework.security: DEBUG
    com.supermarket.pricelistmanagement: DEBUG
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html


