server:
  port: 8085
  servlet:
    context-path: /shop-management
spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:shop_management_db}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
#    username: ${DB_USER:postgres}
#    password: ${DB_PASSWORD:12345678}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/user-management
application:
  security:
    jwt:
      secret-key: zev0iMN5s/ivmYNVO7A2Xo6HD7nvRZom15lfnqoeKgQ=
      expiration: 86400000 # 24 hours in milliseconds
logging:
  level:
    org.springframework.security: DEBUG
    com.supermarket.shopmanagement: DEBUG
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html