apiVersion: v1
kind: ConfigMap
metadata:
  name: customer-management-init-sql
data:
  init.sql: |
    ---- Create extension for UUID generation
    CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

    -- Customers table
    CREATE TABLE customers (
        id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
        company_name VARCHAR(100) NOT NULL,
        contact_person VARCHAR(100) NOT NULL,
        address TEXT NOT NULL,
        email VARCHAR(100) NOT NULL UNIQUE,
        phone_number VARCHAR(20) NOT NULL,
        vat_registration_number VARCHAR(50) UNIQUE,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

    -- Indexes
    CREATE INDEX idx_customers_email ON customers(email);
    CREATE INDEX idx_customers_company_name ON customers(company_name);
