apiVersion: apps/v1
kind: Deployment
metadata:
  name: price-list-management-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: price-list-management-db
  template:
    metadata:
      labels:
        app: price-list-management-db
    spec:
      containers:
        - name: price-list-management-db
          image: postgres:15
          env:
            - name: POSTGRES_DB
              value: price_list_management_db
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_PASSWORD
          volumeMounts:
            - name: init-sql
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: init-sql
          configMap:
            name: price-list-management-init-sql
---
apiVersion: v1
kind: Service
metadata:
  name: price-list-management-db
spec:
  selector:
    app: price-list-management-db
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: price-list-management-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: price-list-management-service
  template:
    metadata:
      labels:
        app: price-list-management-service
    spec:
      containers:
        - name: price-list-management-service
          image: price-list-management-service:1.2
          imagePullPolicy: Never
          ports:
            - containerPort: 8084
          env:
            - name: DB_HOST
              value: price-list-management-db
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: price_list_management_db
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_PASSWORD
            - name: PRODUCT_MANAGEMENT_URL
              value: http://product-management-service:8083/product-management
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-credentials
                  key: JWT_SECRET_KEY
            - name: JWT_EXPIRATION
              valueFrom:
                secretKeyRef:
                  name: jwt-credentials
                  key: JWT_EXPIRATION
            - name: JWT_REFRESH_TOKEN_EXPIRATION
              valueFrom:
                secretKeyRef:
                  name: jwt-credentials
                  key: JWT_REFRESH_TOKEN_EXPIRATION
---
apiVersion: v1
kind: Service
metadata:
  name: price-list-management-service
spec:
  selector:
    app: price-list-management-service
  ports:
    - port: 8084
      targetPort: 8084
  type: ClusterIP