apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
data:
  DB_USER: cG9zdGdyZXM=
  DB_PASSWORD: MTIzNDU2Nzg=
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-credentials
type: Opaque
data:
  JWT_SECRET_KEY: emV2MGlNTjVzL2l2bVlOVk83QTJYbzZIRDdudlJab20xNWxmbnFvZUtnUT0=
  JWT_EXPIRATION: ODY0MDAwMDA=
  JWT_REFRESH_TOKEN_EXPIRATION: NjA0ODAwMDAw
---
apiVersion: v1
kind: Secret
metadata:
  name: app-credentials
type: Opaque
data:
  JASYPT_PASSWORD: bXlMb2NhbFBhc3N3b3JkMTIz