apiVersion: apps/v1
kind: Deployment
metadata:
  name: shop-management-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shop-management-db
  template:
    metadata:
      labels:
        app: shop-management-db
    spec:
      containers:
      - name: shop-management-db
        image: postgres:15
        env:
        - name: POSTGRES_DB
          value: shop_management_db
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: DB_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: DB_PASSWORD
        volumeMounts:
        - name: init-sql
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: init-sql
        configMap:
          name: shop-management-init-sql
---
apiVersion: v1
kind: Service
metadata:
  name: shop-management-db
spec:
  selector:
    app: shop-management-db
  ports:
  - port: 5432
    targetPort: 5432
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shop-management-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shop-management-service
  template:
    metadata:
      labels:
        app: shop-management-service
    spec:
      containers:
      - name: shop-management-service
        image: shop-management-service:1.0
        imagePullPolicy: Never
        ports:
        - containerPort: 8085
        env:
        - name: DB_HOST
          value: shop-management-db
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: shop_management_db
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: DB_PASSWORD
        - name: JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: jwt-credentials
              key: JWT_SECRET_KEY
        - name: JWT_EXPIRATION
          valueFrom:
            secretKeyRef:
              name: jwt-credentials
              key: JWT_EXPIRATION
        - name: JWT_REFRESH_TOKEN_EXPIRATION
          valueFrom:
            secretKeyRef:
              name: jwt-credentials
              key: JWT_REFRESH_TOKEN_EXPIRATION
---
apiVersion: v1
kind: Service
metadata:
  name: shop-management-service
spec:
  selector:
    app: shop-management-service
  ports:
  - port: 8085
    targetPort: 8085
  type: ClusterIP