services:
  user-management-db:
    image: postgres:15
    container_name: user-management-db
    environment:
      POSTGRES_DB: user_management_dbs
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - user-management-data:/var/lib/postgresql/data
      - ./scripts/init_customer_product.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - supermarket-network

  user-management-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: user-management-service
    ports:
      - "8081:8081"
    environment:
      DB_HOST: user-management-db
      DB_PORT: 5432
      DB_NAME: user_management_dbs
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
      JWT_REFRESH_TOKEN_EXPIRATION: ${JWT_REFRESH_TOKEN_EXPIRATION}
    depends_on:
      - user-management-db
    networks:
      - supermarket-network

networks:
  supermarket-network:
    driver: bridge

volumes:
  user-management-data: